language: php

matrix:
  include:
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic

install:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/phpunit
